# SPDX-License-Identifier: MPL-2.0
name: ClusterFuzzLite PR
on:
  pull_request:
    paths:
      - '**/*.rs'
permissions:
  contents: read
jobs:
  PR:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, undefined]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
      - uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          sanitizer: ${{ matrix.sanitizer }}
          language: rust
      - uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 300
          sanitizer: ${{ matrix.sanitizer }}
          mode: code-change
          output-sarif: true
      - uses: github/codeql-action/upload-sarif@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v3
        if: always()
        with:
          sarif_file: vulnerabilities.sarif
