# SPDX-License-Identifier: MPL-2.0
# This workflow is managed by gh actions-lock.
name: ClusterFuzzLite Batch
on:
  schedule:
    - cron: '0 0 * * 0'
permissions:
  actions: read
  contents: read
jobs:
  BatchFuzzing:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, undefined]
    steps:
 uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          sanitizer: ${{ matrix.sanitizer }}
          language: rust
      - uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 1800
          sanitizer: ${{ matrix.sanitizer }}
          mode: batch
          output-sarif: true
      - uses: github/codeql-action/upload-sarif@v4.37.6
        if: always()
        with:
          sarif_file: vulnerabilities.sarif
